# GotToVote Config

country: "Moçambique"
election_year: "2018"

registration_end_date: "-"

api_key: "AIzaSyB7yJRhV-SiMV4q7JB8yJI8HEeorZsN6jI"
table_id: "185jGBDNVE_QCbmsCckaIOu6aXbPFdlLPrI9X6MHm"

url: https://votar.ntatebda.com   # with the https protocol
enforce_ssl: votar.ntatenda.com   # without any protocol

google_analytics: 'UA-110579932-1'

openafrica_url: 'http://africaopendata.org/dataset/voter-registration-2016'

# ------------------------------------------------------------------------------
# Jekyll Config

# Handling Reading
safe: true

# Conversion
highlighter: rouge
