# GotToVote Config

country: "Moçambique"
election_year: "2018"

registration_end_date: "17th May 2018"

api_key: "AIzaSyB7yJRhV-SiMV4q7JB8yJI8HEeorZsN6jI"
table_id: "1XaP18PUbjYXOEpLV1O-1tPvxSlKcIUU4cRA_Pih1"

url: https://eleitor.ntatenda.com   # with the https protocol


google_analytics: 'UA-110579932-1'

url: 'eleitor.ntatenda.com'

# ------------------------------------------------------------------------------
# Jekyll Config

# Handling Reading
safe: true

# Conversion
highlighter: rouge

